In [25]:
### Chi-squared test comparing the Sex of COVID-19 positive individuals with those who are negative

import pandas as pd
from scipy import stats
from scipy.stats import chi2_contingency
import numpy as np

data = pd.read_csv(r'D:\DATA\Python\2\Data.csv')

# Create a contingency table
contingency_table = pd.crosstab(data['Sex'], data['Target'])

# Perform Chi-squared test
chi2, pval, dof, expected = chi2_contingency(contingency_table)

# Print the results
print("Chi-squared test results for Sex:")
print("Chi-squared statistic:", format(chi2, '.2f'))
# print("p-value:", pval)
print("p-value:", format(pval, '.2f'),"\n ----------------------------")
print("\n Observed frequencies:\n", contingency_table)


import numpy as np
from np import array

# define your table as a 2D numpy array
# provide a way to efficiently store and manipulate large amounts of data.
table = array(contingency_table)

# find the sum of every column
# axis=0 for sum of every coulmn and axis=1 for sum of every row
column_sums = np.sum(table, axis=0)
Percentage_frequency=(contingency_table /column_sums)*100


# print("\nPercentage_frequency:\n",Percentage_frequency)
# Round the values in the array to 2 decimal places.
rounded_Percentage = np.array(Percentage_frequency)
for row in rounded_Percentage:
    for i in range(len(row)):
        row[i] = round(row[i], 2)
print("\nPercentage_frequency:\n",rounded_Percentage,"\n ----------------------------")

# Total
row_sums = np.sum(table, axis=1)
print("\nTotal:\n",row_sums)

# Round the values in the array to 2 decimal places.
Percentage_frequencyN=(row_sums /sum(row_sums))*100
PercentageN = np.array(Percentage_frequencyN)
rounded_Percentage = np.round(PercentageN, decimals=2)
print(rounded_Percentage)


Chi-squared test results for Sex:
Chi-squared statistic: 3.06
p-value: 0.08 
 ----------------------------

 Observed frequencies:
 Target   No  Yes
Sex             
Female  609  166
Male    478  101

Percentage_frequency:
 [[56.03 62.17]
 [43.97 37.83]] 
 ----------------------------

Total:
 [775 579]
[57.24 42.76]


In [6]:
### Chi-squared test comparing the Education of COVID-19 positive individuals with those who are negative


# Create a contingency table
contingency_table = pd.crosstab(data['Education'], data['Target'])

# Perform Chi-squared test
chi2, pval, dof, expected = chi2_contingency(contingency_table)

# Print the results
print("Chi-squared test results for Education:\n")
print("Chi-squared statistic:", format(chi2, '.2f'))
print("p-value:", format(pval, '.2f'),"\n ----------------------------")
print("\n Observed frequencies:\n", contingency_table,"\n ----------------------------")
print("\n Expected:\n", expected,"\n ----------------------------")

# define your table as a 2D numpy array
table = np.array(contingency_table)

# find the sum of every column
column_sums = np.sum(table, axis=0)
Percentage_frequency=(contingency_table /column_sums)*100

# round to 2 decimals
rounded_Percentage = np.array(Percentage_frequency)
for row in rounded_Percentage:
    for i in range(len(row)):
        row[i] = round(row[i], 2)

print("\nPercentage_frequency:\n",rounded_Percentage,"\n ----------------------------")


# Total
row_sums = np.sum(table, axis=1)
print("\nTotal:\n",row_sums)

# Round the values in the array to 2 decimal places.
Percentage_frequencyN=(row_sums /sum(row_sums))*100
PercentageN = np.array(Percentage_frequencyN)
rounded_Percentage = np.round(PercentageN, decimals=2)
print(rounded_Percentage)


Chi-squared test results for Education:

Chi-squared statistic: 9.09
p-value: 0.17 
 ----------------------------

 Observed frequencies:
 Target                    No  Yes
Education                        
College                  306   91
Elementary School         88   21
Graduate School           84   23
High School              386   78
Middle School             90   15
No School                 13    2
Two-Three Years College  120   37 
 ----------------------------

 Expected:
 [[318.71418021  78.28581979]
 [ 87.50590842  21.49409158]
 [ 85.90029542  21.09970458]
 [372.50221566  91.49778434]
 [ 84.29468242  20.70531758]
 [ 12.04209749   2.95790251]
 [126.04062038  30.95937962]] 
 ----------------------------

Percentage_frequency:
 [[28.15 34.08]
 [ 8.1   7.87]
 [ 7.73  8.61]
 [35.51 29.21]
 [ 8.28  5.62]
 [ 1.2   0.75]
 [11.04 13.86]] 
 ----------------------------

Total:
 [397 109 107 464 105  15 157]
[29.32  8.05  7.9  34.27  7.75  1.11 11.6 ]


In [7]:
### Chi-squared test comparing the height of COVID-19 positive individuals with those who are negative


# Create a contingency table
contingency_table = pd.crosstab(data['Height'], data['Target'])

# Perform Chi-squared test
chi2, pval, dof, expected = chi2_contingency(contingency_table)

# Print the results
print("Chi-squared test results for Height:")
print("Chi-squared statistic:", format(chi2, '.2f'))
# print("p-value:", pval)
print("p-value:", format(pval, '.2f'),"\n ----------------------------")
print("\n Observed frequencies:\n", contingency_table)


# define your table as a 2D numpy array
table = np.array(contingency_table)

# find the sum of every column
# axis=0 for sum of every coulmn and axis=1 for sum of every row
column_sums = np.sum(table, axis=0)
Percentage_frequency=(contingency_table /column_sums)*100


#print("\nPercentage_frequency:\n",Percentage_frequency)

rounded_Percentage = np.array(Percentage_frequency)
for row in rounded_Percentage:
    for i in range(len(row)):
        row[i] = round(row[i], 2)

print("\nPercentage_frequency:\n",rounded_Percentage,"\n ----------------------------")

# Total
row_sums = np.sum(table, axis=1)
print("\nTotal:\n",row_sums)

# Round the values in the array to 2 decimal places.
Percentage_frequencyN=(row_sums /sum(row_sums))*100
PercentageN = np.array(Percentage_frequencyN)
rounded_Percentage = np.round(PercentageN, decimals=2)
print(rounded_Percentage)

Chi-squared test results for Height:
Chi-squared statistic: 9.21
p-value: 0.03 
 ----------------------------

 Observed frequencies:
 Target        No  Yes
Height               
High         358   74
Low          212   73
Middle High  291   62
Middle Low   226   58

Percentage_frequency:
 [[32.93 27.72]
 [19.5  27.34]
 [26.77 23.22]
 [20.79 21.72]] 
 ----------------------------

Total:
 [432 285 353 284]
[31.91 21.05 26.07 20.97]


In [8]:
### Chi-squared test comparing the Job of COVID-19 positive individuals with those who are negative

import pandas as pd
from scipy.stats import chi2_contingency

# Create a contingency table
contingency_table = pd.crosstab(data['Job'], data['Target'])

# Perform Chi-squared test
chi2, pval, dof, expected = chi2_contingency(contingency_table)

# Print the results
print("Chi-squared test results for Job:\n")
print("Chi-squared statistic:", format(chi2, '.2f'))
print("p-value:", format(pval, '.2f'),"\n ----------------------------")
print("\n Observed frequencies:\n", contingency_table,"\n ----------------------------")

# define your table as a 2D numpy array
table = np.array(contingency_table)

# find the sum of every column
column_sums = np.sum(table, axis=0)
Percentage_frequency=(contingency_table /column_sums)*100


rounded_Percentage = np.array(Percentage_frequency)
for row in rounded_Percentage:
    for i in range(len(row)):
        row[i] = round(row[i], 2)

print("\nPercentage_frequency:\n",rounded_Percentage,"\n ----------------------------")


# Total
row_sums = np.sum(table, axis=1)
print("\nTotal:\n",row_sums)

# Round the values in the array to 2 decimal places.
Percentage_frequencyN=(row_sums /sum(row_sums))*100
PercentageN = np.array(Percentage_frequencyN)
rounded_Percentage = np.round(PercentageN, decimals=2)
print(rounded_Percentage)

Chi-squared test results for Job:

Chi-squared statistic: 10.24
p-value: 0.00 
 ----------------------------

 Observed frequencies:
 Target   No  Yes
Job             
No      696  142
Yes     391  125 
 ----------------------------

Percentage_frequency:
 [[64.03 53.18]
 [35.97 46.82]] 
 ----------------------------

Total:
 [838 516]
[61.89 38.11]


In [19]:
### Chi-squared test comparing the Marry of COVID-19 positive individuals with those who are negative

# Create a contingency table
data = pd.read_csv(r'D:\DATA\Python\2\Data.csv')
contingency_table = pd.crosstab(data['Marry'], data['Target'])

# Perform Chi-squared test
chi2, pval, dof, expected = chi2_contingency(contingency_table)

# Print the results
print("Chi-squared test results for Marry:\n")
print("Chi-squared statistic:", format(chi2, '.2f'))
print("p-value:", format(pval, '.2f'),"\n ----------------------------")
print("\n Observed frequencies:\n", contingency_table,"\n ----------------------------")

# define your table as a 2D numpy array
import numpy as np
table = np.array(contingency_table)

# find the sum of every column
column_sums = np.sum(table, axis=0)
Percentage_frequency=(contingency_table /column_sums)*100

# round to 2 decimals
rounded_Percentage = np.array(Percentage_frequency)
for row in rounded_Percentage:
    for i in range(len(row)):
        row[i] = round(row[i], 2)

print("\nPercentage_frequency:\n",rounded_Percentage,"\n ----------------------------")

# Total
row_sums = np.sum(table, axis=1)
print("\nTotal:\n",row_sums)

# Round the values in the array to 2 decimal places.
Percentage_frequencyN=(row_sums /sum(row_sums))*100
PercentageN = np.array(Percentage_frequencyN)
rounded_Percentage = np.round(PercentageN, decimals=2)
print(rounded_Percentage)




Chi-squared test results for Marry:

Chi-squared statistic: 28.81
p-value: 0.00 
 ----------------------------

 Observed frequencies:
 Target   No  Yes
Marry           
No      210   93
Yes     877  174 
 ----------------------------

Percentage_frequency:
 [[19.32 34.83]
 [80.68 65.17]] 
 ----------------------------

Total:
 [ 303 1051]
[22.38 77.62]


In [9]:
### Chi-squared test comparing the Bckground_history of COVID-19 positive individuals with those who are negative

# Create a contingency table
contingency_table = pd.crosstab(data['Bckground_history'], data['Target'])

# Perform Chi-squared test
chi2, pval, dof, expected = chi2_contingency(contingency_table)

# Print the results
print("Chi-squared test results for Bckground_history:\n")
print("Chi-squared statistic:", format(chi2, '.2f'))
print("p-value:", format(pval, '.2f'),"\n ----------------------------")
print("\n Observed frequencies:\n", contingency_table,"\n ----------------------------")

# define your table as a 2D numpy array
table = np.array(contingency_table)

# find the sum of every column
column_sums = np.sum(table, axis=0)
Percentage_frequency=(contingency_table /column_sums)*100

# round to 2 decimals
rounded_Percentage = np.array(Percentage_frequency)
for row in rounded_Percentage:
    for i in range(len(row)):
        row[i] = round(row[i], 2)

print("\nPercentage_frequency:\n",rounded_Percentage,"\n ----------------------------")


# Total
row_sums = np.sum(table, axis=1)
print("\nTotal:\n",row_sums)

# Round the values in the array to 2 decimal places.
Percentage_frequencyN=(row_sums /sum(row_sums))*100
PercentageN = np.array(Percentage_frequencyN)
rounded_Percentage = np.round(PercentageN, decimals=2)
print(rounded_Percentage)


Chi-squared test results for Bckground_history:

Chi-squared statistic: 0.11
p-value: 0.74 
 ----------------------------

 Observed frequencies:
 Target              No  Yes
Bckground_history          
No                 397   94
Yes                690  173 
 ----------------------------

Percentage_frequency:
 [[36.52 35.21]
 [63.48 64.79]] 
 ----------------------------

Total:
 [491 863]
[36.26 63.74]


In [10]:
### Chi-squared test comparing the Smoking of COVID-19 positive individuals with those who are negative


# Create a contingency table
contingency_table = pd.crosstab(data['Smoking'], data['Target'])

# Perform Chi-squared test
chi2, pval, dof, expected = chi2_contingency(contingency_table)

# Print the results
print("Chi-squared test results for Smoking:\n")
print("Chi-squared statistic:", format(chi2, '.2f'))
print("p-value:", format(pval, '.2f'),"\n ----------------------------")
print("\n Observed frequencies:\n", contingency_table,"\n ----------------------------")

# define your table as a 2D numpy array
table = np.array(contingency_table)

# find the sum of every column
column_sums = np.sum(table, axis=0)
Percentage_frequency=(contingency_table /column_sums)*100

# round to 2 decimals
rounded_Percentage = np.array(Percentage_frequency)
for row in rounded_Percentage:
    for i in range(len(row)):
        row[i] = round(row[i], 2)

print("\nPercentage_frequency:\n",rounded_Percentage,"\n ----------------------------")



# Total
row_sums = np.sum(table, axis=1)
print("\nTotal:\n",row_sums)

# Round the values in the array to 2 decimal places.
Percentage_frequencyN=(row_sums /sum(row_sums))*100
PercentageN = np.array(Percentage_frequencyN)
rounded_Percentage = np.round(PercentageN, decimals=2)
print(rounded_Percentage)



Chi-squared test results for Smoking:

Chi-squared statistic: 20.98
p-value: 0.00 
 ----------------------------

 Observed frequencies:
 Target    No  Yes
Smoking          
Current  129   60
No       708  146
Past     250   61 
 ----------------------------

Percentage_frequency:
 [[11.87 22.47]
 [65.13 54.68]
 [23.   22.85]] 
 ----------------------------

Total:
 [189 854 311]
[13.96 63.07 22.97]


In [11]:

### Chi-squared test comparing the reading of COVID-19 positive individuals with those who are negative

# Create a contingency table
contingency_table = pd.crosstab(data['reading'], data['Target'])

# Perform Chi-squared test
chi2, pval, dof, expected = chi2_contingency(contingency_table)

# Print the results
print("Chi-squared test results for reading:\n")
print("Chi-squared statistic:", format(chi2, '.2f'))
print("p-value:", format(pval, '.2f'),"\n ----------------------------")
print("\n Observed frequencies:\n", contingency_table,"\n ----------------------------")

# define your table as a 2D numpy array
table = np.array(contingency_table)

# find the sum of every column
column_sums = np.sum(table, axis=0)
Percentage_frequency=(contingency_table /column_sums)*100

# round to 2 decimals
rounded_Percentage = np.array(Percentage_frequency)
for row in rounded_Percentage:
    for i in range(len(row)):
        row[i] = round(row[i], 2)

print("\nPercentage_frequency:\n",rounded_Percentage,"\n ----------------------------")



# Total
row_sums = np.sum(table, axis=1)
print("\nTotal:\n",row_sums)

# Round the values in the array to 2 decimal places.
Percentage_frequencyN=(row_sums /sum(row_sums))*100
PercentageN = np.array(Percentage_frequencyN)
rounded_Percentage = np.round(PercentageN, decimals=2)
print(rounded_Percentage)



Chi-squared test results for reading:

Chi-squared statistic: 19.11
p-value: 0.00 
 ----------------------------

 Observed frequencies:
 Target    No  Yes
reading          
Bad      764  223
Good      51    8
Middle   272   36 
 ----------------------------

Percentage_frequency:
 [[70.29 83.52]
 [ 4.69  3.  ]
 [25.02 13.48]] 
 ----------------------------

Total:
 [987  59 308]
[72.9   4.36 22.75]


In [12]:
### Chi-squared test comparing the writing of COVID-19 positive individuals with those who are negative

# Create a contingency table
contingency_table = pd.crosstab(data['writing'], data['Target'])

# Perform Chi-squared test
chi2, pval, dof, expected = chi2_contingency(contingency_table)

# Print the results
print("Chi-squared test results for writing:\n")
print("Chi-squared statistic:", format(chi2, '.2f'))
print("p-value:", format(pval, '.2f'),"\n ----------------------------")
print("\n Observed frequencies:\n", contingency_table,"\n ----------------------------")

# define your table as a 2D numpy array
table = np.array(contingency_table)

# find the sum of every column
column_sums = np.sum(table, axis=0)
Percentage_frequency=(contingency_table /column_sums)*100

# round to 2 decimals
rounded_Percentage = np.array(Percentage_frequency)
for row in rounded_Percentage:
    for i in range(len(row)):
        row[i] = round(row[i], 2)

print("\nPercentage_frequency:\n",rounded_Percentage,"\n ----------------------------")


# Total
row_sums = np.sum(table, axis=1)
print("\nTotal:\n",row_sums)

# Round the values in the array to 2 decimal places.
Percentage_frequencyN=(row_sums /sum(row_sums))*100
PercentageN = np.array(Percentage_frequencyN)
rounded_Percentage = np.round(PercentageN, decimals=2)
print(rounded_Percentage)





Chi-squared test results for writing:

Chi-squared statistic: 0.40
p-value: 0.53 
 ----------------------------

 Observed frequencies:
 Target    No  Yes
writing          
No       671  171
Yes      416   96 
 ----------------------------

Percentage_frequency:
 [[61.73 64.04]
 [38.27 35.96]] 
 ----------------------------

Total:
 [842 512]
[62.19 37.81]


In [13]:
### Chi-squared test comparing the Age of COVID-19 positive individuals with those who are negative

# Create a contingency table
contingency_table = pd.crosstab(data['AgeG'], data['Target'])

# Perform Chi-squared test
chi2, pval, dof, expected = chi2_contingency(contingency_table)

# Print the results
print("Chi-squared test results for AgeG:\n")
print("Chi-squared statistic:", format(chi2, '.2f'))
print("p-value:", format(pval, '.2f'),"\n ----------------------------")
print("\n Observed frequencies:\n", contingency_table,"\n ----------------------------")

# define your table as a 2D numpy array
table = np.array(contingency_table)

# find the sum of every column
column_sums = np.sum(table, axis=0)
Percentage_frequency=(contingency_table /column_sums)*100

# round to 2 decimals
rounded_Percentage = np.array(Percentage_frequency)
for row in rounded_Percentage:
    for i in range(len(row)):
        row[i] = round(row[i], 2)

print("\nPercentage_frequency:\n",rounded_Percentage,"\n ----------------------------")


# Total
row_sums = np.sum(table, axis=1)
print("\nTotal:\n",row_sums)

# Round the values in the array to 2 decimal places.
Percentage_frequencyN=(row_sums /sum(row_sums))*100
PercentageN = np.array(Percentage_frequencyN)
rounded_Percentage = np.round(PercentageN, decimals=2)
print(rounded_Percentage)




Chi-squared test results for AgeG:

Chi-squared statistic: 36.63
p-value: 0.00 
 ----------------------------

 Observed frequencies:
 Target   No  Yes
AgeG            
31-41   134   47
41-51   177   36
51-61   223   51
61-71   208   42
<31     158   70
>70     187   21 
 ----------------------------

Percentage_frequency:
 [[12.33 17.6 ]
 [16.28 13.48]
 [20.52 19.1 ]
 [19.14 15.73]
 [14.54 26.22]
 [17.2   7.87]] 
 ----------------------------

Total:
 [181 213 274 250 228 208]
[13.37 15.73 20.24 18.46 16.84 15.36]


In [20]:
### Leven test and Mannwhitney test comparing the Blood of COVID-19 positive individuals with those who are negative


from scipy.stats import levene
from scipy.stats import mannwhitneyu
from scipy.stats import sem
from numpy import mean

# Create a contingency table
data = pd.read_csv(r'D:\DATA\Python\2\Data.csv')
# Introduce groups
Group1 = data.loc[data['Target'] == 'No'] 
Group1List = list(Group1['Blood'])
Group2 = data.loc[data['Target'] == 'Yes'] 
Group2List = list(Group2['Blood'])

# Levene test
stat0, p_value0 = levene(Group1List, Group2List)
print('p-value levene test:', p_value0,"\n ----------------------------")

# Mannwhitney test
stat1, p_value1 = mannwhitneyu(Group1List, Group2List)
print('stat:', round(stat1,2))
print('p-value:', round(p_value1,2))

mean1 = mean(Group1List)
mean2 = mean(Group2List)
se1 = sem(Group1List)
se2 = sem(Group2List)

print("mean1:",round(mean1,2),"\n","mean2:",round(mean2,2))
print("Standard error1:",round(se1,2),"\n","Standard error2:",round(se2,2),"\n ----------------------------")

# Total
# extract the column of interest into a numpy array
data = data['Blood'].to_numpy()
mean = mean(data)
se = sem(data)
print("mean:",round(mean,2),"\n", "Standard error:", round(se,2))






p-value levene test: 0.0010081858145533614 
 ----------------------------
stat: 144191.5
p-value: 0.87
mean1: 23.81 
 mean2: 24.08
Standard error1: 0.1 
 Standard error2: 0.24 
 ----------------------------
mean: 23.87 
 Standard error: 0.1


In [21]:
### Leven test and T test comparing the biomarker_1 of COVID-19 positive individuals with those who are negative
import pandas as pd
from scipy import stats
from scipy.stats import levene
import numpy as np

data = pd.read_csv(r'D:\DATA\Python\2\Data.csv')
# Introduce groups
Group1 = data.loc[data['Target'] == 'No'] 
Group1List = list(Group1['biomarker_1'])
Group2 = data.loc[data['Target'] == 'Yes'] 
Group2List = list(Group2['biomarker_1'])

# Levene test
stat0, p_value0 = levene(Group1List, Group2List)
print('p-value levene test:', p_value0,"\n ----------------------------")

# T test
t_statistic, p_value = stats.ttest_ind(Group1List, Group2List)

print('t-statistic:', round(t_statistic,2))
print('p-value:', round(p_value,2))


mean1 = np.mean(Group1List)
mean2 = np.mean(Group2List)
se1 = stats.sem(Group1List)
se2 = stats.sem(Group2List)

print("mean1:",round(mean1,2),"\n","mean2:",round(mean2,2))
print("Standard error1:",round(se1,2),"\n","Standard error2:",round(se2,2),"\n ----------------------------")

# Total
# extract the column of interest into a numpy array
data = data['biomarker_1'].to_numpy()
mean = np.mean(data)
se = stats.sem(data)
print("mean:",round(mean,2),"\n", "Standard error:", round(se,2))



# create 95% confidence interval
data = np.array(data)
ci=stats.t.interval(confidence=0.95, df=len(data)-1,loc=mean,scale=se)
print ("ci=",ci)





p-value levene test: 0.8082281842424432 
 ----------------------------
t-statistic: 0.39
p-value: 0.7
mean1: 1818.6 
 mean2: 1797.5
Standard error1: 24.08 
 Standard error2: 47.68 
 ----------------------------
mean: 1814.44 
 Standard error: 21.49
ci= (1772.280863618132, 1856.6025337230787)


In [26]:
### Leven test and T test comparing the biomarker_2 of COVID-19 positive individuals with those who are negative

# Introduce groups
Group1 = data.loc[data['Target'] == 'No'] 
Group1List = list(Group1['biomarker_2'])
Group2 = data.loc[data['Target'] == 'Yes'] 
Group2List = list(Group2['biomarker_2'])

# Levene test
stat0, p_value0 = levene(Group1List, Group2List)
print('p-value levene test:', p_value0,"\n ----------------------------")

# T test
t_statistic, p_value = stats.ttest_ind(Group1List, Group2List)
print('t-statistic:', round(t_statistic,2))
print('p-value:', round(p_value,2))

mean1 = np.mean(Group1List)
mean2 = np.mean(Group2List)
se1 = stats.sem(Group1List)
se2 = stats.sem(Group2List)

print("mean1:",round(mean1,2),"\n","mean2:",round(mean2,2))
print("Standard error1:",round(se1,2),"\n","Standard error2:",round(se2,2),"\n ----------------------------")

# Total
# extract the column of interest into a numpy array
data = data['biomarker_2'].to_numpy()
mean = np.mean(data)
se = stats.sem(data)
print("mean:",round(mean,2),"\n", "Standard error:", round(se,2))





p-value levene test: 0.9842079952533427 
 ----------------------------
t-statistic: 1.01
p-value: 0.31
mean1: 981.02 
 mean2: 942.66
Standard error1: 16.9 
 Standard error2: 33.0 
 ----------------------------
mean: 973.46 
 Standard error: 15.05


In [27]:
### Leven test and T test comparing the biomarker_3 of COVID-19 positive individuals with those who are negative


data = pd.read_csv(r'D:\DATA\Python\2\Data.csv')

# Introduce groups
Group1 = data.loc[data['Target'] == 'No'] 
Group1List = list(Group1['biomarker_3'])
Group2 = data.loc[data['Target'] == 'Yes'] 
Group2List = list(Group2['biomarker_3'])


# Levene test
stat0, p_value0 = levene(Group1List, Group2List)
print('p-value levene test:', p_value0,"\n ----------------------------")

# T test
t_statistic, p_value = stats.ttest_ind(Group1List, Group2List)
print('t-statistic:', round(t_statistic,2))
print('p-value:', round(p_value,2))

mean1 = np.mean(Group1List)
mean2 = np.mean(Group2List)
se1 = stats.sem(Group1List)
se2 = stats.sem(Group2List)

print("mean1:",round(mean1,2),"\n","mean2:",round(mean2,2))
print("Standard error1:",round(se1,2),"\n","Standard error2:",round(se2,2),"\n ----------------------------")

# Total
# extract the column of interest into a numpy array
data = data['biomarker_3'].to_numpy()
mean = np.mean(data)
se = stats.sem(data)
print("mean:",round(mean,2),"\n", "Standard error:", round(se,2))


p-value levene test: 0.4296014297219686 
 ----------------------------
t-statistic: 1.31
p-value: 0.19
mean1: 69.0 
 mean2: 65.6
Standard error1: 1.17 
 Standard error2: 2.22 
 ----------------------------
mean: 68.33 
 Standard error: 1.03
